name: Test

on: [push]

env:
  SOME_ENV: "value of env variable"

jobs:
  get-message:
    name: A job to get message
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
     
      - name: pwd and ls
        run: |
          pwd
          ls
          
      - name: Write in new file
        env:
          S_ENV: ${{ secrets.SOME }}
        run: |  
          echo ${{ env.S_ENV }} > file.txt
      
